name: 'PR Section'
description: 'Dynamically add markdown to your PR description in sections'
author: 'Garrett Cox'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  section-name:
    description: 'Section to add to PR, should be unique, will not be visible'
    required: true
  section-value:
    description: 'Value to display in this section, should be markdown compatible'

runs:
  using: 'node12'
  main: 'dist/index.js'
